USE [master]
GO

/****** Object:  Database [GestionHospitaliereDB ]    Script Date: 25/09/2026 21:03:43 ******/
CREATE DATABASE [GestionHospitaliereDB ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GestionHospitaliereDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GestionHospitaliereDB .mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GestionHospitaliereDB _log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GestionHospitaliereDB _log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GestionHospitaliereDB ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GestionHospitaliereDB ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET ARITHABORT OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET RECOVERY FULL 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET  MULTI_USER 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GestionHospitaliereDB ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GestionHospitaliereDB ] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GestionHospitaliereDB ] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GestionHospitaliereDB ] SET  READ_WRITE 
GO


